version: "3.8"
services:
  golang:
    build:
      context: .
      dockerfile: ./docker/golang/Dockerfile
      # args:
      #   - GROUP_ID=${GROUP_ID}
        # USER_ID: $USER_ID
        # APP_USER: $APP_USER
        # APP_GROUP: $APP_GROUP
        # APP_HOME: $APP_HOME
    container_name: geferti_golang
    depends_on:
      - db
    # env_file: ./docker.env
    # environment:
    ports:
      - 443:443
    volumes:
      - ./:/app

  db:
    image: mysql:latest
    container_name: geferti_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: geferti
      MYSQL_USER: gefertiapp
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/conf/my.cnf:/etc/mysql/mysql.conf.d
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
